// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BookingsColumns holds the columns for the "bookings" table.
	BookingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "full_name", Type: field.TypeString, Nullable: true},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "room", Type: field.TypeString, Nullable: true},
		{Name: "no_of_guests", Type: field.TypeString, Nullable: true},
		{Name: "check_in", Type: field.TypeString, Nullable: true},
		{Name: "check_out", Type: field.TypeString, Nullable: true},
		{Name: "pickup", Type: field.TypeEnum, Nullable: true, Enums: []string{"yes", "no"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"confirmed", "pending"}, Default: "pending"},
		{Name: "payment_status", Type: field.TypeEnum, Enums: []string{"paid", "pending"}, Default: "pending"},
		{Name: "special_requests", Type: field.TypeString, Nullable: true},
	}
	// BookingsTable holds the schema information for the "bookings" table.
	BookingsTable = &schema.Table{
		Name:       "bookings",
		Columns:    BookingsColumns,
		PrimaryKey: []*schema.Column{BookingsColumns[0]},
	}
	// TodosColumns holds the columns for the "todos" table.
	TodosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// TodosTable holds the schema information for the "todos" table.
	TodosTable = &schema.Table{
		Name:       "todos",
		Columns:    TodosColumns,
		PrimaryKey: []*schema.Column{TodosColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BookingsTable,
		TodosTable,
	}
)

func init() {
}
