// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bookings is the predicate function for bookings builders.
type Bookings func(*sql.Selector)

// Todo is the predicate function for todo builders.
type Todo func(*sql.Selector)
