version: "3.9"

services:
  andurar-api:
    build: ../andurar
    restart: always
    volumes:
      - ../andurar:/app
      - ./mnt/storage:/app/storage
    env_file:
      - ../andurar/.env
    depends_on:
      - db
      - webserver
    networks:
      - "andurar.api.net"

  db:
    image: mariadb:11.1.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: andurar!23
      TZ: Afica/Accra
    ports:
      - "3306"
    volumes:
      - ./scripts/database:/docker-entrypoint-initdb.d/:rw
      - ./scripts/mysql.cnf:/etc/my.cnf:ro
      - ./mnt/database:/var/lib/mysql
    networks:
      - "andurar.api.net"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "10000:80"

    environment:
      - PMA_HOST=db
    volumes:
      - /sessions
      - ~/docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    depends_on:
      - db
      - webserver
    networks:
      - "andurar.api.net"

  webserver:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3007:80"
    networks:
      - "andurar.api.net"

networks:
  andurar.api.net:
volumes:
  database:
  storage:
  nginx:
